-- create
CREATE TABLE MEMBER (
  ID INTEGER,
  FIRST_NAME VARCHAR(10),
  LAST_NAME VARCHAR(10),
  MOVIE_ID INTEGER
  
);


CREATE TABLE MEM (
  ID INTEGER,
  TITLE VARCHAR(100),
  CATEGORY VARCHAR(100)
 
  
);
-- insert
INSERT INTO MEMBER VALUES (0001, 'Clark', 'Smith', 01);
INSERT INTO MEMBER VALUES (0002, 'Dave', 'Kumar', 02);
INSERT INTO MEMBER VALUES (0003, 'Ava', 'Pong',   05);
INSERT INTO MEMBER VALUES (0004, 'Ava', 'Pong',   10);
INSERT INTO MEMBER VALUES (0005, 'Ava', 'Pong',   04);


INSERT INTO MEM VALUES (1, 'ASSASINS CREED EMBERS', 'ANIMATON');
INSERT INTO MEM VALUES (2, 'REAL STEEL(2012)'     ,  'ANIMATON');
INSERT INTO MEM VALUES (3, 'ALVIN AND CHIPMUNKS'  , 'ANIMATON');
INSERT INTO MEM VALUES (4, 'THE ADVENTURES OF TIN TIN','ANIMATON');
INSERT INTO MEM VALUES (5, 'SAFE(2012)'           , 'ACTION');
INSERT INTO MEM VALUES (6, 'SAFE HOUSE'           , 'ACTION');
INSERT INTO MEM VALUES (7, 'GIA'                  , '18+');
INSERT INTO MEM VALUES (8, 'DEADLINE'             , '18+');
INSERT INTO MEM VALUES (9, 'THE DIRTY PICTURE'    , '18+');
INSERT INTO MEM VALUES (10, 'MARLEY AMD ME'        , 'ROMANCE');



-- fetch 
SELECT * FROM MEMBER ;
SELECT * FROM MEM;

SELECT * FROM MEM CROSS JOIN MEMBER;

SELECT MEMBER. FIRST_NAME, MEMBER. LAST_NAME, 
MEM. TITLE FROM MEMBER , MEM WHERE MEM. ID = MEMBER. MOVIE_ID;

SELECT  A.TITLE , B.FIRST_NAME , B. LAST_NAME
FROM MEM AS A LEFT JOIN MEMBER AS B ON B. MOVIE_ID = A. ID;

SELECT A. FIRST_NAME , A. LAST_NAME, B.TITLE
FROM MEMBER AS A RIGHT JOIN MEM AS B ON B. ID = A.MOVIE_ID;
